# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ff04b692ad199f0a52219b58070518a4ab2a49622d4603f06ec3db5c872ed7c869a9d091641f5f2222d102b17bc8a74bfcce6613ea82837a694df43f68ac25f

test:
  secret_key_base: 3d7ab96792927acbd5c0d036dd966db8e8e81da88dcd3a406d1943f7a9c2557423be443aa4b383a9bc8ebf2683893edac21050e511fb9bead730f5b702362601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
